services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_DATABASE=actuator
      - MYSQL_USER=example
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=super_secret
    ports:
      - "3306:3306"