services:
  db-product:
    image: mysql:8.0
    container_name: db-product
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: zair
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_product

  db-inventory:
    image: postgres:16
    container_name: db-inventory
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zair
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms_inventory

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
